// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAlB2-p-CxBdd3XHE9GDYgmKeE7w92iSFk",
    authDomain: "tabcontrollersample.firebaseapp.com",
    databaseURL: "https://tabcontrollersample-default-rtdb.firebaseio.com",
    projectId: "tabcontrollersample",
    storageBucket: "tabcontrollersample.firebasestorage.app",
    messagingSenderId: "557413471801",
    appId: "1:557413471801:web:54ae57600e219cf1c85fe8",
    measurementId: "G-06736KPZHW",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBp_2fJLQRKMhlvlAHjgpfsE23qur0Bry4",
    appId: "1:557413471801:android:2b84f6d11dc4205dc85fe8",
    messagingSenderId: "557413471801",
    projectId: "tabcontrollersample",
    databaseURL: "https://tabcontrollersample-default-rtdb.firebaseio.com",
    storageBucket: "tabcontrollersample.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASWu2YwYzKhFS3WEFT54QFcHlxM37Z2D8',
    appId: "1:557413471801:android:2b84f6d11dc4205dc85fe8",
    messagingSenderId: "557413471801",
    projectId: "tabcontrollersample",
    databaseURL: "https://tabcontrollersample-default-rtdb.firebaseio.com",
    storageBucket: "tabcontrollersample.firebasestorage.app",
    iosBundleId: 'com.example.appverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASWu2YwYzKhFS3WEFT54QFcHlxM37Z2D8',
    appId: "1:557413471801:android:2b84f6d11dc4205dc85fe8",
    messagingSenderId: "557413471801",
    projectId: "tabcontrollersample",
    databaseURL: "https://tabcontrollersample-default-rtdb.firebaseio.com",
    storageBucket: "tabcontrollersample.firebasestorage.app",
    iosBundleId: 'com.example.appverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-i9r-zeXvG70xPH37HyDXnHGLa-9c2IQ',
    appId: '1:940090864678:web:4a2f21f56453ee79eda2e7',
    messagingSenderId: '940090864678',
    projectId: 'tabcontroller-6f0fc',
    authDomain: 'tabcontroller-6f0fc.firebaseapp.com',
    databaseURL:
        'https://tabcontroller-6f0fc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tabcontroller-6f0fc.firebasestorage.app',
    measurementId: 'G-9FX4T8FHQK',
  );
}
